#!/usr/bin/env python3

# --- README ---
#
# To start at boot, you can either setup a cron tab as following:
# Edit crontabs by running the command: 
#     crontab -e
# And add to file:
#     @reboot python3 /home/somik/status/server.py 9888 > /home/somik/status/logs.txt 2>&1 &
#
# Or set it up in /etc/rc.local [before] the "exit 0" line as following:
# Edit rc.local file by running the command: 
#     sudo nano /etc/rc.local
# And add to file:
#     @reboot python3 /home/somik/status/server.py 9888 > /home/somik/status/logs.txt 2>&1 &
#
# Note: You do NOT need to run it as sudo
#



from http.server import BaseHTTPRequestHandler, HTTPServer
import time
import subprocess
import os
from os.path import exists
import json
import shutil
import argparse
import base64
import socket


html_page = """
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<title>status</title>
	<style type="text/css">
		* {
			margin: 0;
			padding: 0;
			font-family: 'Arial';
		}

		body {
			min-width: 780px;
			background-color: #EEE;
			color: #777;
			font-size: 16px;
		}

		ul {
			list-style-type: none;
		}

		progress {
			width: 100%;
			margin-top: 5px;
		}

		progress::-webkit-progress-value {
			background: #8C5;
		}

		progress,
		progress::-webkit-progress-bar {
			background-color: #F8F8F8;
		}

		.box {
			margin-bottom: 10px;
			padding: 10px;
			background-color: #FFF;
			box-shadow: 0px 5px 5px -5px #BBB;
		}

		.box:last-child {
			margin-bottom: 0;
		}

		.title {
			margin: 0 5px 5px;
			text-transform: uppercase;
			text-align: center;
			font-size: 12px;
		}

		.value {
			color: #0AF;
		}

		#sidebar {
			position: fixed;
			top: 0;
			left: 0;
			width: 150px;
			height: 100%;
			padding-top: 10px;
			background-color: #222;
		}

		#sidebar .title {
			color: #EEE;
		}

		#sidebar ul {
			margin-bottom: 10px;
		}

		#sidebar ul li {
			padding: 10px;
			background-color: #292929;
			color: #FE3D1D;
			border-bottom: #333 solid 1px;
		}

		#sidebar ul li:first-child {
			border-top: #333 solid 1px;
		}

		#sidebar ul li.online {
			color: #90C95F;
			border-right: #90C95F solid 3px;
		}

		#main {
			margin-left: 150px;
			padding: 10px;
		}

		#cpu li {
			margin-bottom: 5px;
		}

		#cpu li:last-child {
			margin-bottom: 0;
		}

		#footer,
		#footer a {
			color: #777;
			font-size: 12px;
		}

		#footer {
			text-align: center;
		}

		.progress_bar {
			width: 100%;
			border: 1px solid black;
			position: relative;
			padding: 2px 2px 4px 2px;
			background-color: #e2e2e2;
			height: 16px;
			border-radius: 8px;
		}

		.bar1_box,
		.bar2_box {
			background-color: #5cb85c;
			float: left;
			text-align: center;
			padding-top: 2px;
			color: #ffffff;
			font-size: 10pt;
			height: 16px;
			border-radius: 6px;
			overflow: hidden;
		}

		.bar2_box {
			background-color: #5bc0de;
		}
	</style>
</head>

<body onload="load_data()">

	<div id="sidebar">
		<div class="title">services</div>
		<ul id="services">
			<li class="online">HTTP</li>
			<li>SSH</li>
			<li>Samba</li>
		</ul>
	</div>

	<div id="main">

		<div class="title">uptime</div>
		<div id="uptime" class="box">
			<div>
				<span id="uptime-days" class="value">[days]</span> days,
				<span id="uptime-hours" class="value">[hours]</span> hours,
				<span id="uptime-minutes" class="value">[mins]</span> minutes and
				<span id="uptime-seconds" class="value">[secs]</span> seconds
			</div>
		</div>

		<div class="title">cpu load</div>
		<div id="cpu" class="box">
			<ul>
				<li><span id="cpuload-1" class="value"></span> (average over the last 1 minute)</li>
				<li><span id="cpuload-5" class="value"></span> (average over the last 5 minutes)</li>
				<li><span id="cpuload-15" class="value"></span> (average over the last 15 minutes)</li>
			</ul>
		</div>

		<div class="title">Memory <span id="mem_total" style="font-weight: bolder;"></span></div>
		<div id="meminfo" class="box">
			<div>
				<div class="progress_bar">
					<div class="bar1_box" id="mem_used_box"></div>
					<div class="bar2_box" id="mem_cached_box"></div>
				</div>
			</div>
		</div>

		<div class="title">Disk space <span id="disk_total" style="font-weight: bolder;"></span></div>
		<div id="diskinfo" class="box">
			<div>
				<div class="progress_bar">
					<div class="bar1_box" id="disk_used_box"></div>
					<div class="bar2_box" id="disk_cached_box"></div>
				</div>
			</div>
		</div>

		<div class="title">software</div>
		<div id="software" class="box">
			<ul>
				<li>Server Hostname: <span class="value">[hostname]</span></li>
				<li>Server IP: <span class="value">[ip]</span></li>
				<li>Operating System: <span class="value">[os]</span></li>
				<li>Webserver: <span class="value">Unknown</span></li>
				<li>CPU: <span class="value">[cpu]</span></li>
			</ul>
		</div>

		<div id="footer">
			<a href="https://somik.org/">Powered by Somik.org</a>
		</div>
	</div>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
	<script type="text/javascript">
		setInterval(function () {
			load_data();
		}, 2000);
		setInterval(function () {

			if (parseInt($('#uptime-seconds').html()) === 59) {
				$('#uptime-seconds').html(0);
				if (parseInt($('#uptime-minutes').html()) === 59) {
					$('uptime-minutes').html(0);
					if (parseInt($('#uptime-hours').html()) === 23) {
						$('#uptime-hours').html(0);
						$('#uptime-days').html(parseInt($('#uptime-days').html()) + 1);
					} else {
						$('#uptime-hours').html(parseInt($('#uptime-hours').html()) + 1);
					}
				} else {
					$('#uptime-minutes').html(parseInt($('#uptime-minutes').html()) + 1);
				}
			} else {
				$('#uptime-seconds').html(parseInt($('#uptime-seconds').html()) + 1);
			}

		}, 1000);
		function load_data() {
			$.get('/data', function (data) {
            
                var tmp = JSON.stringify(data);
                info = JSON.parse(tmp);

				services = info[0];
				services_length = services.length;
				var i = 0;
				$('#services li').each(function () {
					if (services[i] === true) {
						$(this).not('.online').addClass('online');
					}
					else {
						if ($(this).hasClass('online')) {
							$(this).removeClass('online');
						}
					}

					i++;
				});

				servers = info[1];
				servers_length = services.length;
				var i = 0;
				$('#servers li').each(function () {
					if (servers[i] === true) {
						$(this).not('.online').addClass('online');
					}
					else {
						if ($(this).hasClass('online')) {
							$(this).removeClass('online');
						}
					}

					i++;
				});

				cpuload = info[2];
				$('#cpuload-1').html(cpuload[0]);
				$('#cpuload-5').html(cpuload[1]);
				$('#cpuload-15').html(cpuload[2]);

				memory_progress(info[3]);
				disk_progress(info[4]);

			});
		}
		function memory_progress(mem) {
			var used_box = (mem['usage'] / mem['total'] * 100);
			var cached_box = (mem['cached'] / mem['total'] * 100);
			var used_txt = used_box / 2;
			var cached_txt = (cached_box / 2) + used_box;

			$('#mem_used_box').html(mem['usage'] + " " + mem['tag']);
			$('#mem_cached_box').html(mem['cached'] + " " + mem['tag'] + " (Cached)");
			document.getElementById("mem_used_box").style.width = used_box + "%";
			document.getElementById("mem_cached_box").style.width = cached_box + "%";
			document.getElementById("mem_total").innerHTML = "[Total " + mem['total'] + " " + mem['tag'] + "]";
		}
		function disk_progress(disk) {
			var used_box = (disk['usage'] / disk['total'] * 100);
			var used_txt = used_box / 2;

			$('#disk_used_box').html(disk['usage'] + " " + disk['tag']);
			document.getElementById("disk_used_box").style.width = used_box + "%";
			document.getElementById("disk_total").innerHTML = "[Total " + disk['total'] + " " + disk['tag'] + "]";
		}
	</script>
</body>

</html>
"""


favicon_ico = "AAABAAMAEBAAAAEAIABoBAAANgAAACAgAAABACAAKBEAAJ4EAAAwMAAAAQAgAGgmAADGFQAAKAAAABAAAAAgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAGYAAABmAAAAZgAAAGYAAABmAAAAZgAAAF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAABlAAAApQAAAN8AAADfAAAApQAAAGUAAABcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3AAAAyAAAAMoAAADKAAAAygAAAMoAAADKAAAAygAAAMoAAADKAAAAygAAAMoAAADIAAAAeAAAAAAAAAAkAAAAugAAAAYAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAwAAAK0AAAAlAAAAMgAAAJkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYAAAAMwAAADIAAACZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmAAAADMAAAAyAAAAmQAAAEAAAAB6AAAAegAAACUAAAA/AAAAtQAAAL4AAAAAAAAAQQAAAHoAAAB6AAAAQAAAAJgAAAAzAAAAMgAAAJkAAAAnAAAAUAAAAGUAAACwAAAAqwAAADEAAACxAAAAKAAAAMMAAABwAAAAUAAAACcAAACYAAAAMwAAADIAAACZAAAAAAAAAAAAAAAAAAAAsAAAAL8AAAAAAAAATgAAAJwAAADnAAAAAwAAAAAAAAAAAAAAmAAAADMAAAAyAAAAmQAAAAAAAAAAAAAAAAAAACQAAAAxAAAAAAAAAAQAAADjAAAAqAAAAAAAAAAAAAAAAAAAAJgAAAAzAAAAMgAAAJkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdQAAAE4AAAAAAAAAAAAAAAAAAACYAAAAMwAAADEAAACaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmQAAADMAAAAQAAAA0QAAAGwAAABmAAAAZgAAAGYAAABmAAAAZgAAAGYAAABmAAAAZgAAAGYAAABmAAAAawAAANAAAAAQAAAAAAAAACEAAABjAAAAZQAAAGUAAABlAAAAZQAAAGUAAABlAAAAZQAAAGUAAABlAAAAZQAAAGMAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAACAAAABAAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAApwAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAqAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAClAAAAywAAAMsAAADLAAAA1AAAAP4AAAD/AAAA/wAAAP8AAAD/AAAA/wAAANUAAADLAAAAywAAAMsAAACmAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAsgAAAMAAAADAAAAAwAAAAMAAAACyAAAAEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAE0AAACRAAAAmgAAAJoAAACaAAAAmgAAAJoAAACaAAAAmgAAAJoAAACaAAAAmgAAAJoAAACaAAAAmgAAAJoAAACaAAAAmgAAAJoAAACaAAAAmgAAAJoAAACaAAAAmgAAAJIAAABOAAAAAQAAAAAAAAAAAAAAAAAAAAAAAACSAAAA/gAAAPwAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAPoAAAD6AAAA+gAAAP4AAACTAAAAAAAAAAAAAAAAAAAALwAAAP0AAACvAAAAFgAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAALAAAAhQAAAP0AAAAxAAAAAAAAAAAAAABhAAAA/wAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1AAAA/wAAAGMAAAAAAAAAAAAAAGQAAAD/AAAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAAAD/AAAAZwAAAAAAAAAAAAAAZAAAAP8AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAAChAAAAJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAP8AAABnAAAAAAAAAAAAAABkAAAA/wAAADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcQAAAP8AAACNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAAAA/wAAAGcAAAAAAAAAAAAAAGQAAAD/AAAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAADZAAAA/wAAAOcAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAAAD/AAAAZwAAAAAAAAAAAAAAZAAAAP8AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAASgAAAP4AAADJAAAA/gAAAFQAAAAAAAAAAAAAAAAAAAAGAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAP8AAABnAAAAAAAAAAAAAABkAAAA/wAAADMAAAAaAAAA5gAAAPUAAAD1AAAA9QAAAPUAAACXAAAAAAAAAAAAAAC1AAAA8QAAAB8AAADvAAAAtwAAAAAAAAAAAAAAGQAAAOgAAAD1AAAA9QAAAPUAAAD1AAAA5wAAABsAAAAxAAAA/wAAAGcAAAAAAAAAAAAAAGQAAAD/AAAAMwAAAAoAAACTAAAAoQAAAKEAAAChAAAAzQAAAPoAAAApAAAAJgAAAPsAAACXAAAAAAAAAJkAAAD6AAAAIQAAAAAAAABjAAAA/wAAANAAAAChAAAAoQAAAKEAAACTAAAACwAAADEAAAD/AAAAZwAAAAAAAAAAAAAAZAAAAP8AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAA+gAAAKMAAACPAAAA/AAAAC4AAAAAAAAANQAAAP4AAACAAAAAAAAAAKwAAAD/AAAATwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAP8AAABnAAAAAAAAAAAAAABkAAAA/wAAADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkAAAA+gAAAPEAAAC+AAAAAAAAAAAAAAABAAAAzgAAAN8AAAAMAAAA7QAAAPYAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAAAA/wAAAGcAAAAAAAAAAAAAAGQAAAD/AAAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkAAAD6AAAA/gAAAFIAAAAAAAAAAAAAAAAAAABrAAAA/wAAAIgAAAD+AAAAvQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAAAD/AAAAZwAAAAAAAAAAAAAAZAAAAP8AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJEAAAC/AAAABQAAAAAAAAAAAAAAAAAAABMAAAD0AAAA+gAAAP8AAAB1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAP8AAABnAAAAAAAAAAAAAABkAAAA/wAAADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKIAAAD/AAAA/gAAAC4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAAAA/wAAAGcAAAAAAAAAAAAAAGQAAAD/AAAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAP4AAADhAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAAAD/AAAAZwAAAAAAAAAAAAAAZAAAAP8AAAAzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAlQAAAFcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAP8AAABnAAAAAAAAAAAAAABkAAAA/wAAADMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAAAA/wAAAGcAAAAAAAAAAAAAAGMAAAD/AAAAOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYAAAD/AAAAZgAAAAAAAAAAAAAAPgAAAP4AAACQAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAjAAAAP4AAABAAAAAAAAAAAAAAAACAAAAuAAAAP4AAADhAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAM0AAADNAAAAzQAAAN8AAAD+AAAAugAAAAIAAAAAAAAAAAAAAAAAAAAKAAAAfQAAAMMAAADLAAAAywAAAMsAAADLAAAAywAAAMsAAADLAAAAywAAAMsAAADLAAAAywAAAMsAAADLAAAAywAAAMsAAADLAAAAywAAAMsAAADLAAAAywAAAMsAAADLAAAAwwAAAH4AAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAADAAAABgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAABLAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABLAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAMkAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAAzgAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAL0AAADqAAAA6wAAAOsAAADrAAAA6wAAAOwAAAD4AAAA/gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD5AAAA7AAAAOsAAADrAAAA6wAAAOsAAADqAAAAwwAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0AAABJAAAASwAAAEsAAABLAAAASwAAAFEAAAC9AAAA/gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP4AAAC/AAAAVQAAAEsAAABLAAAASwAAAEsAAABJAAAAIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAA3AAAAhwAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAIoAAAA3AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAJQAAAEsAAABZAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABZAAAATQAAACcAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAACDAAAA3QAAAPoAAAD+AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD+AAAA+gAAAOEAAACEAAAAFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJIAAAD5AAAA/gAAAPsAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA9gAAAPYAAAD2AAAA+AAAAP4AAAD5AAAAmwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANgAAAPkAAAD7AAAAtQAAADUAAAAKAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAHAAAAGAAAAHAAAAD0AAAA+gAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAhQAAAP8AAADbAAAAKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAADGAAAA/wAAAJMAAAAAAAAAAAAAAAAAAAAAAAAAoQAAAP8AAAC3AAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACyAAAA/wAAALIAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAKAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAACPAAAA5wAAAHIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0AAADcAAAA/wAAAM4AAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGkAAAD8AAAA/wAAAO0AAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAANsAAAD/AAAA/wAAAPwAAACCAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAP4AAADzAAAA4QAAAP4AAADCAAAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAEAAAAxAAAAcAAAAHYAAAB2AAAAdgAAAHYAAAB2AAAAdgAAAFYAAAAFAAAAAAAAAAAAAAAPAAAAvAAAAP4AAAC6AAAAZgAAAPwAAADzAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAfAAAAHcAAAB2AAAAdgAAAHYAAAB2AAAAdgAAAHIAAAAyAAAAAQAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAkAAAChAAAA+gAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAOcAAAA9AAAAAAAAAAAAAABKAAAA6gAAAPkAAABvAAAACQAAANIAAAD+AAAAqgAAAAAAAAAAAAAAAAAAAAoAAACjAAAA+wAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPsAAACjAAAADwAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAQAAABzAAAA1gAAANsAAADbAAAA2wAAANsAAADcAAAA9QAAAP0AAACPAAAACQAAAAUAAACRAAAA/AAAAOUAAAArAAAAAAAAAGsAAAD8AAAA8wAAACMAAAAAAAAAAAAAABcAAADXAAAA/wAAAPgAAADdAAAA2wAAANsAAADbAAAA2wAAANgAAAB1AAAABgAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAIAAAAHgAAACEAAAAhAAAAIQAAACEAAAAkAAAAngAAAP8AAADcAAAALQAAABkAAADVAAAA/gAAAKMAAAAEAAAAAAAAACEAAADgAAAA/gAAAIcAAAABAAAAAAAAADsAAAD3AAAA/wAAAMMAAAAlAAAAIQAAACEAAAAhAAAAIQAAAB8AAAAIAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAO8AAAD9AAAAkQAAAGMAAAD8AAAA+AAAAC8AAAAAAAAAAAAAAAgAAAChAAAA/gAAANwAAAAYAAAAAAAAAIcAAAD+AAAA/wAAAHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIUAAAD9AAAA8gAAANkAAAD+AAAAsQAAAAAAAAAAAAAAAAAAAAAAAABgAAAA8gAAAPQAAABVAAAABgAAANMAAAD/AAAA+AAAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMAAADcAAAA/gAAAP4AAADzAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAA1QAAAP0AAACXAAAAOgAAAPoAAAD/AAAAywAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAACMAAAA/AAAAP4AAAC9AAAAGAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAjgAAAP8AAADaAAAAoAAAAP4AAAD+AAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AAAA1wAAAO8AAABvAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAPYAAAD9AAAA9QAAAP8AAADzAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAARgAAAFsAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAALIAAAD/AAAA/wAAAP8AAADQAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAAAD5AAAA/wAAAP4AAACfAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMAAADOAAAA/gAAAPoAAABvAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAACOAAAA+gAAAOcAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAaAAAAD4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAowAAAP8AAACzAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAACxAAAA/wAAALUAAAAAAAAAAAAAAAAAAAAAAAAAnwAAAP8AAAC9AAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAC5AAAA/wAAALAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAP4AAADlAAAAPAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAC4AAADjAAAA/gAAAIYAAAAAAAAAAAAAAAAAAAAAAAAAJwAAAOgAAAD+AAAAyQAAAG4AAABRAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABNAAAATQAAAE0AAABQAAAAagAAAMIAAAD+AAAA6wAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAFgAAADzAAAA/gAAAPkAAADzAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADyAAAA8gAAAPIAAADzAAAA+QAAAP4AAAD0AAAAZAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABfAAAAywAAAOYAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA5wAAAM8AAABgAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAFwAAAD4AAABKAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABKAAAAPwAAABoAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="


def get_ip():
    cmd = "hostname -I | cut -d\' \' -f1"
    ip = subprocess.check_output(cmd, shell=True).decode("utf-8")
    return ip.strip()


def get_distro():
    distrosArr = {
        'debian_version': 'Debian',
        'centos-release' : 'CentOS',
        'lsb-release' : 'Ubuntu',
        'redhat-release' : 'Redhat',
        'fedora-release' : 'Fedora',
        'SuSE-release' : 'SUSE',
        'gentoo-release' : 'Gentoo'
        }
    for key in distrosArr:
        release_file = "/etc/" + key
        if(exists(release_file)):
            return distrosArr[key]
    return "Unknown"


def get_uptime():
    with open('/proc/uptime', 'r') as f:
        uptime = float(f.readline().split()[0])
        days = round(uptime / 86400)
        hours = round((uptime / 3600) % 24)
        minutes = round((uptime / 60) % 60)
        seconds = round(uptime % 60)

        return [days,hours,minutes,seconds]


def get_cpu():
    cmd = "cat /proc/cpuinfo | grep -i 'model name' | awk 'NR==2{$1=$2=$3=\"\";print $0}'"
    cpu = subprocess.check_output(cmd, shell=True).decode("utf-8")
    return cpu.strip()


def generate_html():
    uptime = get_uptime()
    hostname = subprocess.check_output("hostname", shell=True).decode("utf-8")
    output = html_page
    output = output.replace("[days]", str(uptime[0]))
    output = output.replace("[hours]", str(uptime[1]))
    output = output.replace("[mins]", str(uptime[2]))
    output = output.replace("[secs]", str(uptime[3]))
    output = output.replace("[hostname]",hostname)
    output = output.replace("[ip]", get_ip())
    output = output.replace("[os]", get_distro())
    output = output.replace("[cpu]", get_cpu())
    return output


def check_open_ports(ports):
    results = []
    for port in ports:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as a_socket:
            location = ("127.0.0.1", port)
            check = a_socket.connect_ex(location)
            results.append(check == 0)
    return results


class MyServer(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/data':
            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.end_headers()

            load1, load5, load15 = os.getloadavg()
            
            cmd = "free -m | grep -i mem | awk '{print $2,$6,$3,$4}'"
            mem = subprocess.check_output(cmd, shell=True).decode("utf-8")
            memArr = mem.split(" ")

            total, used, free = shutil.disk_usage("/")

            port_status = check_open_ports([80,22,139])

            output = [port_status,None,[round(load1,2),round(load5,2),round(load15,2)],{"total":memArr[0],"cached":memArr[1],"usage":memArr[2],"free":memArr[3].strip(),"tag":"MB"},{"total": round(total/1073741824,1),"usage":round(used/1073741824,1),"tag":"GB"}]
            self.wfile.write(bytes(json.dumps(output), "utf-8"))
            return
        
        if self.path == "/":
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()

            self.wfile.write(bytes(generate_html(), "utf-8"))
            return
            
        if self.path == '/favicon.ico':
            self.send_response(200)
            self.send_header('Content-Type', 'image/x-icon')
            self.end_headers()
            self.wfile.write(base64.b64decode(favicon_ico))
            return

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument('--bind', '-b', default='', metavar='ADDRESS', help='Specify alternate bind address [default: all interfaces]')
    parser.add_argument('port', action='store', default=9808, type=int, nargs='?', help='Specify alternate port [default: 9808]')
    args = parser.parse_args()

    hostName = args.bind
    serverPort = args.port

    webServer = HTTPServer((hostName, serverPort), MyServer)
    cmd = "hostname -I | cut -d\' \' -f1"
    IP = subprocess.check_output(cmd, shell=True).decode("utf-8")
    IP = IP.strip()
    print("Server started http://%s:%s" % (IP, serverPort))

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")


